#requires -Version 5.1
<#
TONG Programming Language Setup Script (Windows / PowerShell)

Usage:
  pwsh .\setup.ps1            # Show usage and quick start
  pwsh .\setup.ps1 -Global    # Create a 'tong' command in your PATH (user scope)

This mirrors setup.sh behavior on Windows. No admin rights required.
#>

[CmdletBinding()]
param(
    [switch]$Global,
    [switch]$Quiet
)

function Write-Info($msg) {
    if (-not $Quiet) { Write-Host $msg }
}

try {
    $repoRoot = $PSScriptRoot
    Write-Info "🚀 Setting up TONG - The Ultimate Programming Language"
    Write-Info "=================================================="

    # Ensure Rust is available
    $cargo = Get-Command cargo -ErrorAction SilentlyContinue
    if (-not $cargo) {
        Write-Warning "Rust toolchain not found. Please install Rust from https://rustup.rs and re-run this script."
    }

    if ($Global) {
        Write-Info "Creating user-level shim and updating PATH..."

        $binDir = Join-Path $HOME ".tong/bin"
        if (-not (Test-Path $binDir)) {
            New-Item -ItemType Directory -Path $binDir -Force | Out-Null
        }

        $shimPath = Join-Path $binDir "tong.ps1"

        $shim = @'
# Auto-generated by TONG setup.ps1 (PowerShell shim)
# Runs the Rust tong.exe if available; otherwise builds with cargo first.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Prefer a Rust-built tong.exe if available
$rustCandidates = @(
    (Join-Path $HOME ".cargo\bin\tong.exe"),
    (Join-Path "{REPO_ROOT}" "rust\tong\target\release\tong.exe"),
    (Join-Path "{REPO_ROOT}" "rust\tong\target\debug\tong.exe")
)

foreach ($exe in $rustCandidates) {
    if (Test-Path $exe) {
        & $exe @args
        exit $LASTEXITCODE
    }
}

# If not found, try to build the Rust binary and run it
$cargo = Get-Command cargo -ErrorAction SilentlyContinue
if ($cargo) {
    Push-Location (Join-Path "{REPO_ROOT}" "rust\tong")
    try {
        cargo build --quiet
        $exe = Join-Path (Get-Location) "target\debug\tong.exe"
    }
    finally {
        Pop-Location
    }
    if (Test-Path $exe) {
        & $exe @args
        exit $LASTEXITCODE
    }
}

Write-Error "Could not find or build tong.exe. Please run 'cargo build' inside rust/tong."
exit 1
'@

        # Inject the repository root while preserving $-variables in the shim
        $shim = $shim.Replace('{REPO_ROOT}', $repoRoot)

        Set-Content -Path $shimPath -Value $shim -Encoding UTF8 -Force

        # Ensure the bin directory is in the user's PATH
        $userPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
        if (-not ($userPath -split ';' | Where-Object { $_ -eq $binDir })) {
            $newUserPath = if ([string]::IsNullOrWhiteSpace($userPath)) { $binDir } else { "$userPath;$binDir" }
            [Environment]::SetEnvironmentVariable('PATH', $newUserPath, 'User')
            # Also update current session
            if (-not ($env:PATH -split ';' | Where-Object { $_ -eq $binDir })) { $env:PATH = "$env:PATH;$binDir" }
            Write-Info "✅ Added $binDir to your user PATH"
        }

        Write-Info "✅ TONG is now available as 'tong' (tong.ps1) in new PowerShell sessions"
        Write-Info "   Try: tong --version"
    }
    else {
        Write-Info "Rust-based TONG detected. You can run via:"
        Write-Info "  cargo run --release -p tong -- (path to .tong file)"
        Write-Info "Or run 'pwsh .\\setup.ps1 -Global' to install a 'tong' command in your PATH"
    }

    Write-Host ""
    Write-Host "🎯 Quick Start:"
    Write-Host "  cargo run -p tong -- ../../examples/hello.tong   # Run example"
    Write-Host "  cargo build -p tong --release                   # Build optimized binary"
    Write-Host "  tong ../../examples/hello.tong                  # After -Global shim install"
    Write-Host ""
    Write-Host "📚 Examples available in examples/ directory"
    Write-Host "📖 See README.md for full documentation"
    Write-Host ""
    Write-Host "✨ TONG is ready for heterogeneous computing!"
}
catch {
    Write-Error $_
    exit 1
}
