[package]
name = "tong"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
# Use logos 0.12 for simpler error handling with an Error variant
logos = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
