name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with clippy and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust/tong

      - name: rustfmt (check)
        working-directory: rust/tong
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        working-directory: rust/tong
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build (treat warnings as errors)
        working-directory: rust/tong
        env:
          RUSTFLAGS: -D warnings
        run: cargo build --all-targets --release

      - name: Example regression harness
        run: |
          bash scripts/check_examples.sh
